### ISSUE TITLE
Does not build on development SBCL - SB-KERNEL:PARSE-DEFMACRO is gone

### ISSUE THREAD

**Issue by quicklisp** [Bike/introspect-environment#2]
http://report.quicklisp.org/2015-07-28/failure-report/introspect-environment.html#introspect-environment has a full log.

**Comment by quicklisp** [comment]
Does that mean the project won't work on anything but the 1.2.14+ now?

**Comment by Bike** [comment]
Yes. I wasn't sure of the normal protocol. I could put in a read-time conditional on the version but it would probably be messy?

**Comment by quicklisp** [comment]
Using internals is already pretty messy. Using internals and then breaking it for everyone who isn't on the latest is even more messy. Is there any way to avoid using sbcl internals entirely? (Maybe it's not, due to the nature of the project?)

**Comment by Bike** [comment]
For that particular function I could avoid use of internals by rewriting the sbcl functionality portably. I wanted to avoid that, because the functionality is already there in the image and it would introduce a lot more code in the library, but I can certainly see the appeal.

I'll try to at least conditionalize the versioned internals now.

**Comment by Bike** [comment]
That works on local dev SBCL as well as my distro's SBCL (1.1.14).

In the future I will not close issues in commits despite the coolness of that feature. That was rude of me, sorry.

**Comment by sionescu** [comment]
@Bike: have you seen [parse-declarations](https://common-lisp.net/project/parse-declarations/manual/html_node/parse_002dbody.html) ?
